/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmEmailChangeRouteImport } from './routes/confirm-email-change'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AuthLayoutForgotPasswordRouteImport } from './routes/_auth-layout/forgot-password'
import { Route as AuthLayoutLoginRouteImport } from './routes/_auth-layout/login'
import { Route as AuthLayoutRegisterRouteImport } from './routes/_auth-layout/register'
import { Route as AuthLayoutResetPasswordRouteImport } from './routes/_auth-layout/reset-password'
import { Route as AppNotesIndexRouteImport } from './routes/_app/notes/index'
import { Route as AppNotesNoteIdRouteImport } from './routes/_app/notes/$noteId'
import { Route as AppNotesNewRouteImport } from './routes/_app/notes/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailChangeRoute = ConfirmEmailChangeRouteImport.update({
  id: '/confirm-email-change',
  path: '/confirm-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AuthLayoutForgotPasswordRoute =
  AuthLayoutForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutLoginRoute = AuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutRegisterRoute = AuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutResetPasswordRoute = AuthLayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AppNotesIndexRoute = AppNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNoteIdRoute = AppNotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesNewRoute = AppNotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/reset-password': typeof AuthLayoutResetPasswordRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/notes/new': typeof AppNotesNewRoute
  '/notes/': typeof AppNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/login': typeof AuthLayoutLoginRoute
  '/register': typeof AuthLayoutRegisterRoute
  '/reset-password': typeof AuthLayoutResetPasswordRoute
  '/notes/$noteId': typeof AppNotesNoteIdRoute
  '/notes/new': typeof AppNotesNewRoute
  '/notes': typeof AppNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_auth-layout/forgot-password': typeof AuthLayoutForgotPasswordRoute
  '/_auth-layout/login': typeof AuthLayoutLoginRoute
  '/_auth-layout/register': typeof AuthLayoutRegisterRoute
  '/_auth-layout/reset-password': typeof AuthLayoutResetPasswordRoute
  '/_app/notes/$noteId': typeof AppNotesNoteIdRoute
  '/_app/notes/new': typeof AppNotesNewRoute
  '/_app/notes/': typeof AppNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/auth'
    | '/confirm-email-change'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/notes/$noteId'
    | '/notes/new'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/auth'
    | '/confirm-email-change'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/settings'
    | '/users'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/notes/$noteId'
    | '/notes/new'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth-layout'
    | '/accept-invitation'
    | '/auth'
    | '/confirm-email-change'
    | '/verify-email'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/users'
    | '/_auth-layout/forgot-password'
    | '/_auth-layout/login'
    | '/_auth-layout/register'
    | '/_auth-layout/reset-password'
    | '/_app/notes/$noteId'
    | '/_app/notes/new'
    | '/_app/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AuthRoute: typeof AuthRoute
  ConfirmEmailChangeRoute: typeof ConfirmEmailChangeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email-change': {
      id: '/confirm-email-change'
      path: '/confirm-email-change'
      fullPath: '/confirm-email-change'
      preLoaderRoute: typeof ConfirmEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth-layout/forgot-password': {
      id: '/_auth-layout/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthLayoutForgotPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/login': {
      id: '/_auth-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/register': {
      id: '/_auth-layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthLayoutRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/reset-password': {
      id: '/_auth-layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthLayoutResetPasswordRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_app/notes/': {
      id: '/_app/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppNotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/$noteId': {
      id: '/_app/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof AppNotesNoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes/new': {
      id: '/_app/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AppNotesNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppNotesNoteIdRoute: typeof AppNotesNoteIdRoute
  AppNotesNewRoute: typeof AppNotesNewRoute
  AppNotesIndexRoute: typeof AppNotesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppNotesNoteIdRoute: AppNotesNoteIdRoute,
  AppNotesNewRoute: AppNotesNewRoute,
  AppNotesIndexRoute: AppNotesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLayoutForgotPasswordRoute: typeof AuthLayoutForgotPasswordRoute
  AuthLayoutLoginRoute: typeof AuthLayoutLoginRoute
  AuthLayoutRegisterRoute: typeof AuthLayoutRegisterRoute
  AuthLayoutResetPasswordRoute: typeof AuthLayoutResetPasswordRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutForgotPasswordRoute: AuthLayoutForgotPasswordRoute,
  AuthLayoutLoginRoute: AuthLayoutLoginRoute,
  AuthLayoutRegisterRoute: AuthLayoutRegisterRoute,
  AuthLayoutResetPasswordRoute: AuthLayoutResetPasswordRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AuthRoute: AuthRoute,
  ConfirmEmailChangeRoute: ConfirmEmailChangeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
