import { describe, expect, it } from "vitest";

import { buildDocumentCsp } from "./csp";

const NONCE = "0123456789abcdef0123456789abcdef";

describe("buildDocumentCsp", () => {
  it("allows scripts only through the server nonce", () => {
    const policy = buildDocumentCsp(NONCE, "/api/v1");

    expect(policy).toContain(`script-src 'self' 'nonce-${NONCE}' 'strict-dynamic'`);
    expect(policy).not.toContain("script-src 'self' 'unsafe-inline'");
  });

  it("allows the validated cross-origin API without allowing every HTTP origin", () => {
    const policy = buildDocumentCsp(NONCE, "http://localhost:5156/api/v1");

    expect(policy).toContain("connect-src 'self' ws: wss: https: http://localhost:5156");
    expect(policy).not.toContain("connect-src 'self' http:");
  });

  it("allows the configured direct-upload origin without opening every HTTP origin", () => {
    const policy = buildDocumentCsp(NONCE, "http://localhost:5156/api/v1", "http://127.0.0.1:9000");

    expect(policy).toContain("http://localhost:5156 http://127.0.0.1:9000");
    expect(policy).not.toContain("connect-src 'self' http:");
  });

  it("deduplicates API and upload origins", () => {
    const policy = buildDocumentCsp(
      NONCE,
      "https://app.example.com/api/v1",
      "https://app.example.com",
    );

    expect(policy.match(/https:\/\/app\.example\.com/g)).toHaveLength(1);
  });

  it("keeps a root-relative API on the document origin", () => {
    const policy = buildDocumentCsp(NONCE, "/api/v1");

    expect(policy).toContain("connect-src 'self' ws: wss: https:");
    expect(policy).not.toContain("application.invalid");
  });

  it("rejects values that cannot be generated by the router", () => {
    expect(() => buildDocumentCsp("client-controlled-value", "/api/v1")).toThrow(
      "Invalid server-generated CSP nonce",
    );
  });
});
